### ISSUE TITLE
What is the License of this project?

### ISSUE THREAD

**Issue by IntegerLimit** [gabor7d2/DataFixerExampleMod#1]
Hello, sorry for disturbing you. I would like to know the license of this project, and whether I can use this code as the basis for another of my projects.

The license on that project is LGPLv3.

Of course, I will credit you.

Thanks!

**Comment by IntegerLimit** [comment]
I would like to add: Perhaps it may be wise to add a license on your projects, especially if someone wants to use them, or their code, as legally no one is allowed to use it.

https://choosealicense.com/no-permission/

**Comment by IntegerLimit** [comment]
I've assumed permission for now, as this project is used in GTCE, and someone who knows you said you shared it out so others can use it.

If this is not the case, feel free to comment!

**Comment by gabor7d2** [comment]
Hi, I added a license (Unlicense), feel free to do whatever you want :)

**Comment by IntegerLimit** [comment]
Thanks!
